import { Metadata } from "next";
import "./globals.css";
import { Montserrat } from "next/font/google";
import { Header } from "@/components/header";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Layout project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`bg-[#000] ${montserrat.variable} font-sans h-screen max-w-screen`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
